### ISSUE TITLE
ExLlama Version Compatibility

### ISSUE THREAD

**Issue by ItsJPrentice** [TheBlokeAI/dockerLLM#1]
After yesterday's updates to https://github.com/oobabooga/text-generation-webui, running the base image no longer allowed for running GPTQ images using ExLlama. See the thread below for the issue and resolution. It appears that the version of ExLlama being installed will need to be updated.

https://github.com/oobabooga/text-generation-webui/issues/3004#issue-1788117410

**Comment by TheBloke** [comment]
I fixed this about 30 mins ago - destroy your pods and re-make them and it should work fine now.
