### ISSUE TITLE
Wrong name or cuda version in cuda11.8.0-ubuntu22.04-oneclick/Dockerfile

### ISSUE THREAD

**Issue by michaelwdombek** [TheBlokeAI/dockerLLM#10]
Hey, thanks for you amazing work! 
Yesterday I played around with your oneclick image and noticed that the CUDA_VERSION in the [Dockerfile](https://raw.githubusercontent.com/TheBlokeAI/dockerLLM/848627b314bb1b0b983309b0b81648d06263bbdd/cuda11.8.0-ubuntu22.04-oneclick/Dockerfile) does not match the name of the image.

I'm not sure what combination you desired to create so i created the issue. 

```
ARG CUDA_VERSION="12.1.1"
ARG CUDNN_VERSION="8"
ARG UBUNTU_VERSION="22.04"
ARG DOCKER_FROM=thebloke/cuda$CUDA_VERSION-ubuntu$UBUNTU_VERSION-textgen:latest 
...
```

As far as i tested the image works well with cuda 12.1.1 installed. So this is large issue.

Kind regards
Michael

**Comment by TheBloke** [comment]
Yes I know. This is because changing the name of the container will require getting Runpod to update their template, and I've not had time to coordinate that.

It's mentioned in the README:

![image](https://github.com/TheBlokeAI/dockerLLM/assets/784313/56df65ee-fabb-40f5-9739-38a8d57c68bb)

**Comment by michaelwdombek** [comment]
:man_facepalming: Sorry - didn't check the README, just dropped right into the sub-directory. 

my fault :bowing_man:
