### ISSUE TITLE
TypeError: Llama.create_completion() got an unexpected keyword argument 'seed'

### ISSUE THREAD

**Issue by MattiPaivike** [TheBlokeAI/dockerLLM#11]
Hey,

I am using your RunPod template: `TheBloke Local LLMs One-Click UI and API`

I am getting this error when generating with GGUF models:
```
TypeError: Llama.create_completion() got an unexpected keyword argument 'seed'
```

These exact settings where working before without issues.

I know it is somehow related to latest `text-generation-webui`  changes and someone else was complaining about it:
https://github.com/oobabooga/text-generation-webui/issues/4631 Upgrading `llama-cpp-python` did not help as someone had suggested in that thread.

I was able to fix it by downgrading `text-generation-webui` and `llama-cpp-python` with ssh connection to pod.

**Comment by twilwa** [comment]
mind elaborating on how you did this? i don't see a venv folder and in the cloud shell i'm just getting python not found, so i'm a bit lost, lol.

**Comment by KevinFanwave** [comment]
> mind elaborating on how you did this? i don't see a venv folder and in the cloud shell i'm just getting python not found, so i'm a bit lost, lol.
 
Run it using ctransformers instead, may not address the issue but fixes it for the mean time.

**Comment by makingitup** [comment]
Am receiving a similar error:
TypeError: Llama.create_completion() got an unexpected keyword argument 'min_p'

Just started showing up on runpod, it was working before.
Tried reseting the pod and creating new ones, tried upgrading and downgrading llama_cpp_python, didn't solve it.
Tried switching to ctransformers and it worked, but it's was way too slow to be usable.

**Comment by TheBloke** [comment]
This should have been fixed a while ago now when I rebuilt the pod. Re-open if there's still any issues.
