### ISSUE TITLE
Startup script is installing the wrong requirements

### ISSUE THREAD

**Issue by makingitup** [TheBlokeAI/dockerLLM#12]
When starting a new runpod using 'RunPod TheBloke LLMs' as a template and load any gpu, after running a query it returns no response. Looking in the logs shows this:

Traceback (most recent call last):
File "/workspace/text-generation-webui/modules/callbacks.py", line 57, in gentask
ret = self.mfunc(callback=_callback, *args, **self.kwargs)
File "/workspace/text-generation-webui/modules/llamacpp_model.py", line 141, in generate
completion_chunks = self.model.create_completion(
TypeError: Llama.create_completion() got an unexpected keyword argument 'min_p'

When looking at pip freeze I notice this line:
'https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.2.11+cu121-cp310-cp310-manylinux_2_31_x86_64.whl'

Notice it says llama_cpp_python_cuda-0.2.11
Latest version is 0.2.19

cd into text-generation-webui and run pip install -r requirements.txt

Proper version is installed:
'https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.2.19+cu121-cp311-cp311-manylinux_2_31_x86_64.whl'

Chat now works properly. However, when stopping and restarting the pod, the wrong version is reinstalled again.

**Comment by TheBloke** [comment]
I've just pushed a new docker container - please test and confirm if it fixes the issue. It should, as it rebuilds from requirements.txt and thus should get the latest llama-cpp-python.

**Comment by makingitup** [comment]
It works, thank you so much.
However it requires significantly more storage space now. I could fit it on 10GB before, now it requires more like 30

**Comment by TheBloke** [comment]
Hmm, the image is still under 10GB
![image](https://github.com/TheBlokeAI/dockerLLM/assets/784313/43864bf3-a492-4aea-b215-8df757b79e28)

The previous one was 8.6GB, so it's increased by 0.5GB, not a huge amount

I'll see if there's anything that can be cleaned up in it. But it might just be that more is being installed now.

**Comment by makingitup** [comment]
I tried it again just now and it's back to its previous usage.  Thanks
