### ISSUE TITLE
docker pull thebloke/cuda12.1.1-ubuntu22.04-pytorch denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by superresistant** [TheBlokeAI/dockerLLM#13]
when doing 
`docker pull thebloke/cuda12.1.1-ubuntu22.04-pytorch`
I get
```
denied: requested access to the resource is denied
Error response from daemon: manifest for thebloke/cuda12.1.1-ubuntu22.04-pytorch:latest not found: manifest unknown: manifest unknown
```

trying a different 
`docker pull long24ieccorp/cuda12.1.1-ubuntu22.04-pytorch`
it works

**Comment by TheBloke** [comment]
The PyTorch repo is called `:1` not `:latest` - I never pushed a `:latest` as I only made the pytorch repo as a sub-step of making the `textgen` and `oneclick` repos.

You know that the PyTorch one only contains PyTorch, no inference or even transformers? Is that what you want?

**Comment by TheBloke** [comment]
I just pushed `:latest` as well, so that will work too now

```
(pytorch2)  ubuntu@a10:/workspace ᐅ docker tag thebloke/cuda12.1.1-ubuntu22.04-pytorch:1 thebloke/cuda12.1.1-ubuntu22.04-pytorch:latest
(pytorch2)  ubuntu@a10:/workspace ᐅ docker push thebloke/cuda12.1.1-ubuntu22.04-pytorch:latest
The push refers to repository [docker.io/thebloke/cuda12.1.1-ubuntu22.04-pytorch]
db0bff7a716c: Layer already exists
89e404e93f0e: Layer already exists
638c8d9de20f: Layer already exists
70d32d75fc9f: Layer already exists
0f7c883f1a4f: Layer already exists
7aee75a70a2f: Layer already exists
24e1e08aaa60: Layer already exists
3416903c2cc4: Layer already exists
83687aeafbbf: Layer already exists
83ecbf43a888: Layer already exists
b15b1df4adac: Layer already exists
bea30ebbe843: Layer already exists
8afeff4e91d7: Layer already exists
6ec2b659c9ab: Layer already exists
566cd9dd29d6: Layer already exists
256d88da4185: Layer already exists
latest: digest: sha256:1808e29d42b38e637dfd52e1e03af86495961bd6c236e3bbd0fa038d38b1627f size: 3683
(pytorch2)  ubuntu@a10:/workspace ᐅ
```

**Comment by superresistant** [comment]
Sorry I didn't explain the context, it came when executing the build_oneclick.py
Here is the full quote.
I want to learn to deploy your docker. 

```
#10 naming to docker.io/thebloke/cuda12.1.1-ubuntu22.04-pytorch:1
#10 naming to docker.io/thebloke/cuda12.1.1-ubuntu22.04-pytorch:1 done
#10 DONE 0.0s
2023-12-06 12:29:25 INFO [root] Pushing cuda12.1.1-ubuntu22.04-pytorch using command: docker push thebloke/cuda12.1.1-ubuntu22.04-pytorch:1
The push refers to repository [docker.io/thebloke/cuda12.1.1-ubuntu22.04-pytorch]
1a28f7d7cad4: Preparing 
a51aa039af3d: Preparing 
8bf2364d839c: Preparing 
6a7e743bf135: Preparing 
0f7c883f1a4f: Layer already exists 
7aee75a70a2f: Waiting 
24e1e08aaa60: Waiting 
3416903c2cc4: Waiting 
83687aeafbbf: Waiting 
83ecbf43a888: Waiting 
b15b1df4adac: Waiting 
bea30ebbe843: Waiting 
8afeff4e91d7: Waiting 
6ec2b659c9ab: Waiting 
566cd9dd29d6: Waiting 
256d88da4185: Waiting 
denied: requested access to the resource is denied
2023-12-06 12:29:26 ERROR [root] Got error while executing docker command: Command 'docker push thebloke/cuda12.1.1-ubuntu22.04-pytorch:1' returned non-zero exit status 1.
2023-12-06 12:29:26 ERROR [root] Process aborted due to error running Docker commands
```

**Comment by TheBloke** [comment]
Ah I see, yeah that script isn't really designed for other people to run it.  It's trying to push to my Docker Hub, which won't work of course

If you want to build your own version of the containers, edit build_docker.py and change `thebloke` to your own Docker Hub account.

Is there a need to re-build the containers, like new features or something broken? I can rebuild the main one if so

**Comment by superresistant** [comment]
> Ah I see, yeah that script isn't really designed for other people to run it. It's trying to push to my Docker Hub, which won't work of course
> 
> If you want to build your own version of the containers, edit build_docker.py and change `thebloke` to your own Docker Hub account.
> 
> Is there a need to re-build the containers, like new features or something broken? I can rebuild the main one if so

Ok it makes sense now. Thx.

**Comment by TheBloke** [comment]
No worries. I'll look to add a --username option to that script in future, to make this easier. I have another version of that script which has that, but I didn't update this one yet.
