### ISSUE TITLE
Latest text-generation-webui

### ISSUE THREAD

**Issue by joenas** [TheBlokeAI/dockerLLM#15]
Hey,

Had a quick look at your Dockerfiles but uncertain if it always uses latest `text-generation-webui` or if there is a way to pull that when running? 

Either way I couldn't get `thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest` running because of a missing requirement, same as [this issue](https://github.com/oobabooga/text-generation-webui/issues/5013). It's fixed in [this commit](https://github.com/oobabooga/text-generation-webui/pull/5012/commits/258c695ead3ae8dfcfdd7bdd68f3257ebbf04148).

A workaround is to just install `rich` in a web terminal when running on runpod but.. yeah.

**Comment by TheBloke** [comment]
Thanks for the report. I have rebuilt the docker now which has brought in the new requirement.

To answer your question: the Docker `git pull`s the latest text-generation-webui on each boot, so it's kept up-to-date with latest code.  But it doesn't automatically re-install the requirements - that's only done when the Docker is built.

Therefore when new pip packages are needed, I need to re-build the Docker container.

Please stop and re-start your instance, or kill it and make a new one, to get the latest version of the Docker container.  And let me know if it's working OK now.

**Comment by joenas** [comment]
Works like a charm 🍀

**Comment by TheBloke** [comment]
Great, thanks

**Comment by joenas** [comment]
No, thank you 😄
