### ISSUE TITLE
Can't download model from HF

### ISSUE THREAD

**Issue by langchain4j** [TheBlokeAI/dockerLLM#2]
Hi, thanks a lot for your work!

I am following the [doc](https://github.com/TheBlokeAI/dockerLLM/blob/main/README_Runpod_LocalLLMsUIandAPI.md) and trying to download "TheBloke/vicuna-13b-v1.3-GPTQ" model. I and getting the following error right away when I click "Download":

`Traceback (most recent call last): File “/workspace/text-generation-webui/server.py”, line 134, in download_model_wrapper downloader = downloader_module.ModelDownloader() TypeError: ModelDownloader.init() missing 1 required positional argument: ‘max_retries’`

Am I doing something wrong or is it a bug?
Thanks!

**Comment by TheBloke** [comment]
Thanks for your pledge!

Can you show me a screenshot of what you're entering in the Download box?

**Comment by TheBloke** [comment]
Ah never mind, it's a bug in text-generation-webui https://github.com/oobabooga/text-generation-webui/issues/3009

**Comment by TheBloke** [comment]
Here's how you can manually fix it for yourself, until text-generation-webui is fixed:

1. SSH in or use Web terminal
2. Run the following:
```
cd text-generation-webui
git checkout 333075e726e8216ed35c6dd17a479c44fb4d8691
/root/scripts/restart-text-generation-webui.sh
```

Here's a screenshot showing me running these commands in the Web Terminal, and then successfully downloading a model:

![image](https://github.com/TheBlokeAI/dockerLLM/assets/784313/88a74675-2be2-481f-8ddb-e5dba1091e63)

**Comment by langchain4j** [comment]
Thanks a lot, will try!

**Comment by martinkoeth** [comment]
> Here's how you can manually fix it for yourself, until text-generation-webui is fixed:
> 
>     1. SSH in or use Web terminal
> 
>     2. Run the following:
> 
> 
> ```
> cd text-generation-webui
> git checkout 333075e726e8216ed35c6dd17a479c44fb4d8691
> /root/scripts/restart-text-generation-webui.sh
> ```
> 
> Here's a screenshot showing me running these commands in the Web Terminal, and then successfully downloading a model:
> 
> ![image](https://user-images.githubusercontent.com/784313/251111187-88a74675-2be2-481f-8ddb-e5dba1091e63.png)

Hey, I tried this fix but it doesn't work for me. I'm using windows and got the same exact error as mentioned above. Also wenn manually installing GPT4 x Alpaca it doesn't load properly. Is that a known issue?

**Comment by TheBloke** [comment]
@martinkoeth Are you using my Runpod template?

If you're using my template and followed the steps, please show a screenshot of what you did and in what way it didn't work

**Comment by TheBloke** [comment]
The bug has now been fixed in text-generation-webui: https://github.com/oobabooga/text-generation-webui/commit/88a747b5b9a132ed848f736adaaadc76678d9e35

So I will close this issue now.  Any existing pods will automatically pull the update as soon as they are stopped and started again, except if you followed the workaround above.

For anyone who did follow the workaround above and checked out that specific commit, you can undo it by:
1. SSH in again, or use Web Terminal
2. `cd text-generation-webui`
3. `git checkout main`
4. `git pull`
5. `/root/scripts/restart-text-generation-webui`

Or just delete and re-make the pod.

**Comment by TheBloke** [comment]
For future I'm planning to add a new feature in the pod where the user can specify a commit via Template Override environment variable. This will make situations like this easier to handle in future.
