### ISSUE TITLE
No TLS/SSL on port 5005

### ISSUE THREAD

**Issue by ItsJPrentice** [TheBlokeAI/dockerLLM#3]
When running the container on a platform like Runpod, I noticed it's not possible to establish a websocket connection via TLS/SSL on port 5005 (used for [text-generation-webui](https://github.com/oobabooga/text-generation-webui)'s streaming API by default).

If I understand correctly, this means all traffic over the wire between the client and the remote server is unencrypted. Is it possible to generate a self-signed SSL certificate on container bootstrap so that we can connect via `wss` rather than just `ws`?

**Comment by TheBloke** [comment]
Sorry, I only just saw this.

How would that work exactly?  All I'm doing is launching text-generation-webui's code, which provides the websockets API.  So if a certificate is to be added, wouldn't that require modification to text-generation-webui to tell it to use that certificate?  In which case this would be a request for text-generation-webui.

If this were normal HTTPS then one option would be to have a proxying web server in the middle, eg nginx, which could then host the certificate and pass requests to/from text-generation-webui.  But I'm not sure if that applies to WebSockets?

If you can provide me more details on exactly how this would be implemented then I will have a look at what's involved. But if any code changes are required to text-generation-webui then those should be raised in that repo - I don't want to have to make a fork of it and maintain that.

**Comment by ItsJPrentice** [comment]
Same approach as https. Your example of running Nginx as an upgrade proxy around the default streaming port should work.

I tried the following and was able to get a self-signed certificate working.

https://github.com/TheBlokeAI/dockerLLM/compare/main...ItsJPrentice:dockerLLM:main
