### ISSUE TITLE
GPTQ-for-LLaMa support

### ISSUE THREAD

**Issue by virgulvirgul** [TheBlokeAI/dockerLLM#4]
Do you have any plans to add GPTQ-for-LLaMa?

**Comment by TheBloke** [comment]
I hadn't planned to, no. It'd be quite easy to do so - does it do something that AutoGPTQ or ExLlama doesn't?  I haven't used GPTQ-for-LLaMa myself in months as I use ExLlama for 4-bit Llama models, and AutoGPTQ otherwise.

**Comment by virgulvirgul** [comment]
It provides 4-bits quantization solution for the "FLAN-T5" series and UL2 as well. Do you know of any other solution that does that? I don't have much experience with ExLlama.
