### ISSUE TITLE
A recent llamacpp update has broken GGML models. Manually Updating requirements.txt fixes it, but just wanted you to know

### ISSUE THREAD

**Issue by bangkokpadang** [TheBlokeAI/dockerLLM#6]
Hi.

An update to text-generation-webui, from about a week and a half ago, that added n_gqa support to the text-generation-webui has broken loading GGML models with llamacpp, introducing an 'unexpected argument' when it passes the 'n_gqa' value.

Using the Web terminal or SSH to go in and run `pip install -r requirements --upgrade` from the `workspace/text-generation-webui` directory fixes it, but I just wanted to let you know in case anyone else searches out this issue and/or you wanted to update the requirements in your docker.

Thanks for all the great work you do, you're really carrying a lot of the weight for the whole community right now, and it definitely doesn't go unappreciated.

**Comment by davidbegara** [comment]
You can edit `cuda11.8.0-ubuntu22.04-oneclick/scripts/build-llama-cpp-python.sh` specifying the right version like this `pip3 install --no-cache-dir llama-cpp-python==0.1.78` and build a new image so you don't have to make this change every time you restart your container
